phpcs:
    standard: PSR2
    # number of allowed errors is compared with warnings+errors, or just errors from checkstyle.xml
    ignoreWarnings: false
    # https://github.com/squizlabs/PHP_CodeSniffer/wiki/Reporting
    reports:
        cli:
            - full
        file:
            # checkstyle is always included and overriden
            checkstyle: checkstyle.xml
            # you can include custom reports (https://github.com/wikidi/codesniffer/blob/master/reports/wikidi/Summary.php#L39)
            # ./vendor/owner/package/src/MySummaryReport.php: phpcs-summary.html

php-cs-fixer:
    # http://cs.sensiolabs.org/#usage
    rules: '@PSR2'
    allowRiskyRules: false
    # by default the tool is runned in dry-run mode (no fixers are applied)
    isDryRun: true
    # alternatively you can define path to your .phpcs_file (rules/allowRiskyRules config is ignored)
    config: null

phpmd:
    standard: app/phpmd.xml

phpcpd:
    minLines: 5
    minTokens: 70

phpmetrics:
    config: null

phpstan:
    level: 0
    # https://github.com/phpstan/phpstan#configuration
    # standard: tests/.travis/phpstan.neon

phpunit:
    # binary: vendor/bin/phpunit
    binary: null
    # phpunit.xml
    config: null
    reports:
        file: []
            # log: [junit, tap, json]
            # testdox: [html, text]
            # coverage: [html, clover, crap4j, php, text, xml] # requires XDebug extension

psalm:
    config: null
    deadCode: false
    threads: 1
    showInfo: true

# Php file extensions to parse.
extensions:
    - php

# paths are relative to .phpqa.yml, so don't copy-paste this section if you don't have custom templates
report:
    phploc: app/report/phploc.xsl
    phpcpd: app/report/phpcpd.xsl
    phpcs: app/report/phpcs.xsl
    pdepend: app/report/pdepend.xsl
    phpmd: app/report/phpmd.xsl
    php-cs-fixer: app/report/php-cs-fixer.xsl
    psalm: app/report/psalm.xsl

# you can add new tools, but existing tools cannot be removed
tool:
    phpmetrics: [Edge\QA\Tools\Analyzer\PhpMetrics, Edge\QA\Tools\Analyzer\PhpMetricsV2]
    phploc: Edge\QA\Tools\Analyzer\Phploc
    phpcs: [Edge\QA\Tools\Analyzer\Phpcs, Edge\QA\Tools\Analyzer\PhpcsV3]
    php-cs-fixer: Edge\QA\Tools\Analyzer\PhpCsFixer
    phpmd: Edge\QA\Tools\Analyzer\Phpmd
    pdepend: Edge\QA\Tools\Analyzer\Pdepend
    phpcpd: Edge\QA\Tools\Analyzer\Phpcpd
    parallel-lint: Edge\QA\Tools\Analyzer\ParallelLint
    phpstan: Edge\QA\Tools\Analyzer\Phpstan
    phpunit: Edge\QA\Tools\Analyzer\Phpunit
    psalm: Edge\QA\Tools\Analyzer\Psalm
