#!/usr/bin/env php
<?php

require_once __DIR__ . "/vendor/autoload.php";
require_once __DIR__ . "/RoboFile.php";

// add robo command between the application name and the arguments
array_splice($argv, 1, 0, 'ci');

// IO
$input = new \Symfony\Component\Console\Input\ArgvInput($argv);
$output = new \Symfony\Component\Console\Output\ConsoleOutput();
\Robo\Config::setOutput($output);

// run robo
$robo = new \Robo\Runner();
$qa = $robo->createApplication(RoboFile::class);
$qa->run($input, $output);
