var classes = [
    {
        "name": "Edge\\QA\\IgnoredPathsTest",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "ignore",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "testNoOptionWhenNothingIsIgnored",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "testIgnoreDirectoriesAndFiles",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "provideTools",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 4,
        "nbMethods": 4,
        "nbMethodsPrivate": 1,
        "nbMethodsPublic": 3,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 6,
        "ccn": 3,
        "ccnMethodMax": 2,
        "externals": [
            "PHPUnit_Framework_TestCase",
            "Edge\\QA\\IgnoredPaths"
        ],
        "parents": [
            "PHPUnit_Framework_TestCase"
        ],
        "lcom": 2,
        "length": 137,
        "vocabulary": 61,
        "volume": 812.51,
        "difficulty": 4.6,
        "effort": 3734.7,
        "level": 0.22,
        "bugs": 0.27,
        "time": 207,
        "intelligentContent": 176.77,
        "number_operators": 6,
        "number_operands": 131,
        "number_operators_unique": 4,
        "number_operands_unique": 57,
        "cloc": 5,
        "loc": 30,
        "lloc": 28,
        "mi": 77.21,
        "mIwoC": 47.65,
        "commentWeight": 29.56,
        "kanDefect": 0.22,
        "relativeStructuralComplexity": 9,
        "relativeDataComplexity": 0.94,
        "relativeSystemComplexity": 9.94,
        "totalStructuralComplexity": 36,
        "totalDataComplexity": 3.75,
        "totalSystemComplexity": 39.75,
        "package": "Edge\\QA\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 2,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "Edge\\QA\\ConfigTest",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "testLoadDefaultConfig",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "testBuildAbsolutePath",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "testOverrideDefaultConfig",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "testAllowPartialUpdateOfTools",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "testIgnoreNonExistentUserConfig",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "testNoExceptionWhenCwdHasNoConfig",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "testThrowExceptionWhenFileDoesNotExist",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "testConfigCsvString",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "testUseCwdIfNoDirectoryIsSpecified",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "testThrowExceptionWhenBinaryDoesNotExist",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "testThrowExceptionWhenWrongBinaryIsUsed",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "testMultipleConfig",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "testAutodetectConfigInCurrentDirectory",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "testIgnoreAutodetectedConfigIfUserConfigIsSpecified",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "shouldStopPhpqa",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 15,
        "nbMethods": 15,
        "nbMethodsPrivate": 1,
        "nbMethodsPublic": 14,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 16,
        "ccn": 2,
        "ccnMethodMax": 2,
        "externals": [
            "PHPUnit_Framework_TestCase",
            "Edge\\QA\\Config",
            "Edge\\QA\\Config",
            "Edge\\QA\\Config",
            "Edge\\QA\\Config",
            "Edge\\QA\\Config",
            "Edge\\QA\\Config",
            "Edge\\QA\\Config",
            "Edge\\QA\\Config",
            "Edge\\QA\\Config",
            "Edge\\QA\\Config",
            "Edge\\QA\\Config",
            "Edge\\QA\\Config",
            "Edge\\QA\\Config",
            "Edge\\QA\\Config"
        ],
        "parents": [
            "PHPUnit_Framework_TestCase"
        ],
        "lcom": 11,
        "length": 207,
        "vocabulary": 62,
        "volume": 1232.52,
        "difficulty": 6.21,
        "effort": 7650.12,
        "level": 0.16,
        "bugs": 0.41,
        "time": 425,
        "intelligentContent": 198.57,
        "number_operators": 27,
        "number_operands": 180,
        "number_operators_unique": 4,
        "number_operands_unique": 58,
        "cloc": 1,
        "loc": 135,
        "lloc": 134,
        "mi": 38.34,
        "mIwoC": 31.69,
        "commentWeight": 6.65,
        "kanDefect": 0.22,
        "relativeStructuralComplexity": 64,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 64,
        "totalStructuralComplexity": 960,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 960,
        "package": "Edge\\QA\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 2,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "Edge\\QA\\PathsTest",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "testPathToBinaryIsEscaped",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 1,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "PHPUnit_Framework_TestCase"
        ],
        "parents": [
            "PHPUnit_Framework_TestCase"
        ],
        "lcom": 1,
        "length": 5,
        "vocabulary": 4,
        "volume": 10,
        "difficulty": 0,
        "effort": 0,
        "level": 1.6,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 16,
        "number_operators": 0,
        "number_operands": 5,
        "number_operators_unique": 0,
        "number_operands_unique": 4,
        "cloc": 0,
        "loc": 9,
        "lloc": 9,
        "mi": 72.05,
        "mIwoC": 72.05,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 0,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 0,
        "package": "Edge\\QA\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "Edge\\QA\\RunningToolTest",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "testBuildOptionWithDefinedSeparator",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "testMarkSuccessWhenXPathIsNotDefined",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "testMarkFailureWhenXmlFileDoesNotExist",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "provideAllowedErrorsForNonexistentFile",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "testCompareAllowedCountWithErrorsCountFromXml",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "provideAllowedErrors",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "testRuntimeSelectionOfErrorXpath",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "testAnalyzeExitCodeInCliMode",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "provideProcess",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "testCreateUniqueIdForUserReport",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 10,
        "nbMethods": 10,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 10,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 11,
        "ccn": 2,
        "ccnMethodMax": 2,
        "externals": [
            "PHPUnit_Framework_TestCase",
            "Edge\\QA\\RunningTool",
            "Edge\\QA\\RunningTool",
            "Edge\\QA\\RunningTool",
            "Edge\\QA\\RunningTool",
            "Edge\\QA\\RunningTool",
            "Edge\\QA\\RunningTool",
            "Edge\\QA\\RunningTool"
        ],
        "parents": [
            "PHPUnit_Framework_TestCase"
        ],
        "lcom": 8,
        "length": 131,
        "vocabulary": 48,
        "volume": 731.63,
        "difficulty": 6.57,
        "effort": 4806.64,
        "level": 0.15,
        "bugs": 0.24,
        "time": 267,
        "intelligentContent": 111.36,
        "number_operators": 18,
        "number_operands": 113,
        "number_operators_unique": 5,
        "number_operands_unique": 43,
        "cloc": 3,
        "loc": 66,
        "lloc": 63,
        "mi": 56.64,
        "mIwoC": 40.42,
        "commentWeight": 16.22,
        "kanDefect": 0.22,
        "relativeStructuralComplexity": 81,
        "relativeDataComplexity": 0.37,
        "relativeSystemComplexity": 81.37,
        "totalStructuralComplexity": 810,
        "totalDataComplexity": 3.7,
        "totalSystemComplexity": 813.7,
        "package": "Edge\\QA\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 2,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "Edge\\QA\\ReportTest",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "setUp",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "testConvertTwigToHtml",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "testConvertXmlToHtml",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "provideXml",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "testIgnoreMissingXmlDocuments",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "tearDown",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 6,
        "nbMethods": 6,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 6,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 7,
        "ccn": 2,
        "ccnMethodMax": 2,
        "externals": [
            "PHPUnit_Framework_TestCase"
        ],
        "parents": [
            "PHPUnit_Framework_TestCase"
        ],
        "lcom": 2,
        "length": 47,
        "vocabulary": 24,
        "volume": 215.49,
        "difficulty": 4,
        "effort": 861.97,
        "level": 0.25,
        "bugs": 0.07,
        "time": 48,
        "intelligentContent": 53.87,
        "number_operators": 7,
        "number_operands": 40,
        "number_operators_unique": 4,
        "number_operands_unique": 20,
        "cloc": 1,
        "loc": 38,
        "lloc": 37,
        "mi": 61.62,
        "mIwoC": 49.18,
        "commentWeight": 12.43,
        "kanDefect": 0.22,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 1.33,
        "relativeSystemComplexity": 1.33,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 8,
        "totalSystemComplexity": 8,
        "package": "Edge\\QA\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "Edge\\QA\\OptionsTest",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "setUp",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "overrideOptions",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "testEscapePaths",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "testRespectToolsOrderDefinedInOption",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "testIgnorePdependInCliOutput",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "testIsSuggestedToolInstalled",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "provideInternalClass",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "testBuildOutput",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "provideOutputs",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "testExecute",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "provideExecutionMode",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "testBuildRootPath",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "provideAnalyzedDir",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "testLoadAllowedErrorsCount",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "buildRunningTools",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 15,
        "nbMethods": 15,
        "nbMethodsPrivate": 2,
        "nbMethodsPublic": 13,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 15,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "PHPUnit_Framework_TestCase",
            "Edge\\QA\\Options",
            "Edge\\QA\\Options"
        ],
        "parents": [
            "PHPUnit_Framework_TestCase"
        ],
        "lcom": 5,
        "length": 186,
        "vocabulary": 69,
        "volume": 1136.19,
        "difficulty": 3.77,
        "effort": 4286.52,
        "level": 0.27,
        "bugs": 0.38,
        "time": 238,
        "intelligentContent": 301.16,
        "number_operators": 20,
        "number_operands": 166,
        "number_operators_unique": 3,
        "number_operands_unique": 66,
        "cloc": 6,
        "loc": 88,
        "lloc": 82,
        "mi": 56.4,
        "mIwoC": 36.72,
        "commentWeight": 19.68,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 49,
        "relativeDataComplexity": 0.86,
        "relativeSystemComplexity": 49.86,
        "totalStructuralComplexity": 735,
        "totalDataComplexity": 12.88,
        "totalSystemComplexity": 747.88,
        "package": "Edge\\QA\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 2,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "Edge\\QA\\RoboFile",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [],
        "nbMethodsIncludingGettersSetters": 0,
        "nbMethods": 0,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 0,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 0,
        "ccn": 1,
        "ccnMethodMax": 0,
        "externals": [
            "Robo\\Tasks"
        ],
        "parents": [
            "Robo\\Tasks"
        ],
        "lcom": 0,
        "length": 0,
        "vocabulary": 0,
        "volume": 0,
        "difficulty": 0,
        "effort": 0,
        "level": 0,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 0,
        "number_operators": 0,
        "number_operands": 0,
        "number_operators_unique": 0,
        "number_operands_unique": 0,
        "cloc": 0,
        "loc": 6,
        "lloc": 6,
        "mi": 171,
        "mIwoC": 171,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 0,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 0,
        "package": "Edge\\QA\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "Edge\\QA\\CodeAnalysisTasks",
        "interface": false,
        "abstract": true,
        "final": false,
        "methods": [
            {
                "name": "tools",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "ci",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "normalizeCliOptions",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "loadConfig",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "ciClean",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "runTools",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "toolToExec",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "buildHtmlReport",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "buildSummary",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 9,
        "nbMethods": 9,
        "nbMethodsPrivate": 7,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 29,
        "ccn": 21,
        "ccnMethodMax": 7,
        "externals": [
            "Edge\\QA\\Task\\TableVersions",
            "Edge\\QA\\Config",
            "Edge\\QA\\Tools\\Tools",
            "Edge\\QA\\Options",
            "Edge\\QA\\RunningTool",
            "Edge\\QA\\Task\\AssetsLoader",
            "Edge\\QA\\Task\\TableSummary"
        ],
        "parents": [],
        "lcom": 1,
        "length": 280,
        "vocabulary": 79,
        "volume": 1765.06,
        "difficulty": 9.58,
        "effort": 16901.04,
        "level": 0.1,
        "bugs": 0.59,
        "time": 939,
        "intelligentContent": 184.33,
        "number_operators": 47,
        "number_operands": 233,
        "number_operators_unique": 6,
        "number_operands_unique": 73,
        "cloc": 22,
        "loc": 136,
        "lloc": 114,
        "mi": 58.75,
        "mIwoC": 29.57,
        "commentWeight": 29.18,
        "kanDefect": 1.91,
        "relativeStructuralComplexity": 1156,
        "relativeDataComplexity": 0.16,
        "relativeSystemComplexity": 1156.16,
        "totalStructuralComplexity": 10404,
        "totalDataComplexity": 1.43,
        "totalSystemComplexity": 10405.43,
        "package": "Edge\\QA\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 7,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "Edge\\QA\\Config",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "loadUserConfig",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "loadConfig",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "mergeConfigs",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getCustomBinary",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "value",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "path",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "pathsOrValues",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "csv",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "get",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "findInConfig",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "throwInvalidPath",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 12,
        "nbMethods": 12,
        "nbMethodsPrivate": 5,
        "nbMethodsPublic": 7,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 29,
        "ccn": 18,
        "ccnMethodMax": 4,
        "externals": [
            "Symfony\\Component\\Yaml\\Yaml",
            "RuntimeException",
            "RuntimeException"
        ],
        "parents": [],
        "lcom": 1,
        "length": 210,
        "vocabulary": 51,
        "volume": 1191.21,
        "difficulty": 13.2,
        "effort": 15729.38,
        "level": 0.08,
        "bugs": 0.4,
        "time": 874,
        "intelligentContent": 90.21,
        "number_operators": 44,
        "number_operands": 166,
        "number_operators_unique": 7,
        "number_operands_unique": 44,
        "cloc": 3,
        "loc": 112,
        "lloc": 109,
        "mi": 44.14,
        "mIwoC": 31.6,
        "commentWeight": 12.54,
        "kanDefect": 1.49,
        "relativeStructuralComplexity": 49,
        "relativeDataComplexity": 2.05,
        "relativeSystemComplexity": 51.05,
        "totalStructuralComplexity": 588,
        "totalDataComplexity": 24.63,
        "totalSystemComplexity": 612.63,
        "package": "Edge\\QA\\",
        "pageRank": 0.09,
        "afferentCoupling": 4,
        "efferentCoupling": 2,
        "instability": 0.33,
        "violations": {}
    },
    {
        "name": "Edge\\QA\\OutputMode",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [],
        "nbMethodsIncludingGettersSetters": 0,
        "nbMethods": 0,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 0,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 0,
        "ccn": 1,
        "ccnMethodMax": 0,
        "externals": [],
        "parents": [],
        "lcom": 0,
        "length": 4,
        "vocabulary": 4,
        "volume": 8,
        "difficulty": 0,
        "effort": 0,
        "level": 2,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 16,
        "number_operators": 0,
        "number_operands": 4,
        "number_operators_unique": 0,
        "number_operands_unique": 4,
        "cloc": 0,
        "loc": 8,
        "lloc": 8,
        "mi": 73.84,
        "mIwoC": 73.84,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 0,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 0,
        "package": "Edge\\QA\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 0,
        "instability": 0,
        "violations": {}
    },
    {
        "name": "Edge\\QA\\Options",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "loadOutput",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getCommonRootPath",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getAnalyzedDirs",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "loadTools",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "buildRunningTools",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "sortTools",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "toFile",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "rawFile",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 9,
        "nbMethods": 9,
        "nbMethodsPrivate": 3,
        "nbMethodsPublic": 6,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 21,
        "ccn": 13,
        "ccnMethodMax": 5,
        "externals": [
            "Edge\\QA\\IgnoredPaths",
            "Edge\\QA\\RunningTool"
        ],
        "parents": [],
        "lcom": 1,
        "length": 178,
        "vocabulary": 51,
        "volume": 1009.69,
        "difficulty": 16.22,
        "effort": 16376.71,
        "level": 0.06,
        "bugs": 0.34,
        "time": 910,
        "intelligentContent": 62.25,
        "number_operators": 45,
        "number_operands": 133,
        "number_operators_unique": 10,
        "number_operands_unique": 41,
        "cloc": 9,
        "loc": 95,
        "lloc": 86,
        "mi": 57.97,
        "mIwoC": 35.02,
        "commentWeight": 22.95,
        "kanDefect": 0.75,
        "relativeStructuralComplexity": 25,
        "relativeDataComplexity": 1.65,
        "relativeSystemComplexity": 26.65,
        "totalStructuralComplexity": 225,
        "totalDataComplexity": 14.83,
        "totalSystemComplexity": 239.83,
        "package": "Edge\\QA\\",
        "pageRank": 0.11,
        "afferentCoupling": 6,
        "efferentCoupling": 2,
        "instability": 0.25,
        "violations": {}
    },
    {
        "name": "Edge\\QA\\Tools\\Tool",
        "interface": false,
        "abstract": true,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "__invoke",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "saveDynamicConfig",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "toolVersionIs",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "writeln",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 5,
        "nbMethods": 5,
        "nbMethodsPrivate": 3,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 7,
        "ccn": 3,
        "ccnMethodMax": 2,
        "externals": [
            "Edge\\QA\\Config",
            "Edge\\QA\\Options",
            "Edge\\QA\\RunningTool",
            "Edge\\QA\\Tools\\GetVersions"
        ],
        "parents": [],
        "lcom": 2,
        "length": 52,
        "vocabulary": 21,
        "volume": 228.4,
        "difficulty": 3.42,
        "effort": 780.37,
        "level": 0.29,
        "bugs": 0.08,
        "time": 43,
        "intelligentContent": 66.85,
        "number_operators": 11,
        "number_operands": 41,
        "number_operators_unique": 3,
        "number_operands_unique": 18,
        "cloc": 4,
        "loc": 37,
        "lloc": 33,
        "mi": 74.34,
        "mIwoC": 49.96,
        "commentWeight": 24.38,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 9,
        "relativeDataComplexity": 0.95,
        "relativeSystemComplexity": 9.95,
        "totalStructuralComplexity": 45,
        "totalDataComplexity": 4.75,
        "totalSystemComplexity": 49.75,
        "package": "Edge\\QA\\Tools\\",
        "pageRank": 0.17,
        "afferentCoupling": 13,
        "efferentCoupling": 4,
        "instability": 0.24,
        "violations": {}
    },
    {
        "name": "Edge\\QA\\Tools\\Tools",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "loadTools",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getExecutableTools",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "buildCommand",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getReport",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getAssets",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getSummary",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getVersions",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 8,
        "nbMethods": 8,
        "nbMethodsPrivate": 1,
        "nbMethodsPublic": 7,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 15,
        "ccn": 8,
        "ccnMethodMax": 6,
        "externals": [
            "Edge\\QA\\Config",
            "RuntimeException",
            "Edge\\QA\\Options",
            "Edge\\QA\\RunningTool",
            "Edge\\QA\\Options",
            "handlerClass",
            "Edge\\QA\\RunningTool",
            "Edge\\QA\\Options",
            "Edge\\QA\\Tools\\AnalyzeResults",
            "Edge\\QA\\Tools\\GetVersions"
        ],
        "parents": [],
        "lcom": 1,
        "length": 131,
        "vocabulary": 35,
        "volume": 671.94,
        "difficulty": 8.42,
        "effort": 5655.46,
        "level": 0.12,
        "bugs": 0.22,
        "time": 314,
        "intelligentContent": 79.83,
        "number_operators": 30,
        "number_operands": 101,
        "number_operators_unique": 5,
        "number_operands_unique": 30,
        "cloc": 1,
        "loc": 74,
        "lloc": 73,
        "mi": 47.44,
        "mIwoC": 38.48,
        "commentWeight": 8.96,
        "kanDefect": 0.73,
        "relativeStructuralComplexity": 36,
        "relativeDataComplexity": 1.55,
        "relativeSystemComplexity": 37.55,
        "totalStructuralComplexity": 288,
        "totalDataComplexity": 12.43,
        "totalSystemComplexity": 300.43,
        "package": "Edge\\QA\\Tools\\",
        "pageRank": 0.01,
        "afferentCoupling": 1,
        "efferentCoupling": 7,
        "instability": 0.88,
        "violations": {}
    },
    {
        "name": "Edge\\QA\\Tools\\Analyzer\\Phpmd",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__invoke",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 3,
        "ccn": 3,
        "ccnMethodMax": 3,
        "externals": [
            "Edge\\QA\\Tools\\Tool"
        ],
        "parents": [
            "Edge\\QA\\Tools\\Tool"
        ],
        "lcom": 1,
        "length": 33,
        "vocabulary": 20,
        "volume": 142.62,
        "difficulty": 2.47,
        "effort": 352.36,
        "level": 0.4,
        "bugs": 0.05,
        "time": 20,
        "intelligentContent": 57.73,
        "number_operators": 5,
        "number_operands": 28,
        "number_operators_unique": 3,
        "number_operands_unique": 17,
        "cloc": 0,
        "loc": 14,
        "lloc": 14,
        "mi": 59.51,
        "mIwoC": 59.51,
        "commentWeight": 0,
        "kanDefect": 0.22,
        "relativeStructuralComplexity": 25,
        "relativeDataComplexity": 0.17,
        "relativeSystemComplexity": 25.17,
        "totalStructuralComplexity": 25,
        "totalDataComplexity": 0.17,
        "totalSystemComplexity": 25.17,
        "package": "Edge\\QA\\Tools\\Analyzer\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "Edge\\QA\\Tools\\Analyzer\\Phpcs",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__invoke",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 6,
        "ccn": 6,
        "ccnMethodMax": 6,
        "externals": [
            "Edge\\QA\\Tools\\Tool"
        ],
        "parents": [
            "Edge\\QA\\Tools\\Tool"
        ],
        "lcom": 1,
        "length": 78,
        "vocabulary": 39,
        "volume": 412.26,
        "difficulty": 5.73,
        "effort": 2361.13,
        "level": 0.17,
        "bugs": 0.14,
        "time": 131,
        "intelligentContent": 71.98,
        "number_operators": 15,
        "number_operands": 63,
        "number_operators_unique": 6,
        "number_operands_unique": 33,
        "cloc": 1,
        "loc": 32,
        "lloc": 31,
        "mi": 61.87,
        "mIwoC": 48.35,
        "commentWeight": 13.52,
        "kanDefect": 0.82,
        "relativeStructuralComplexity": 49,
        "relativeDataComplexity": 0.13,
        "relativeSystemComplexity": 49.13,
        "totalStructuralComplexity": 49,
        "totalDataComplexity": 0.13,
        "totalSystemComplexity": 49.13,
        "package": "Edge\\QA\\Tools\\Analyzer\\",
        "pageRank": 0.02,
        "afferentCoupling": 1,
        "efferentCoupling": 1,
        "instability": 0.5,
        "violations": {}
    },
    {
        "name": "Edge\\QA\\Tools\\Analyzer\\PhpcsV3",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [],
        "nbMethodsIncludingGettersSetters": 0,
        "nbMethods": 0,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 0,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 0,
        "ccn": 1,
        "ccnMethodMax": 0,
        "externals": [
            "Edge\\QA\\Tools\\Analyzer\\Phpcs"
        ],
        "parents": [
            "Edge\\QA\\Tools\\Analyzer\\Phpcs"
        ],
        "lcom": 0,
        "length": 9,
        "vocabulary": 9,
        "volume": 28.53,
        "difficulty": 0,
        "effort": 0,
        "level": 2,
        "bugs": 0.01,
        "time": 0,
        "intelligentContent": 57.06,
        "number_operators": 0,
        "number_operands": 9,
        "number_operators_unique": 0,
        "number_operands_unique": 9,
        "cloc": 1,
        "loc": 9,
        "lloc": 8,
        "mi": 94.66,
        "mIwoC": 69.98,
        "commentWeight": 24.69,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 0,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 0,
        "package": "Edge\\QA\\Tools\\Analyzer\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "Edge\\QA\\Tools\\Analyzer\\Phploc",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__invoke",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 2,
        "ccn": 2,
        "ccnMethodMax": 2,
        "externals": [
            "Edge\\QA\\Tools\\Tool"
        ],
        "parents": [
            "Edge\\QA\\Tools\\Tool"
        ],
        "lcom": 1,
        "length": 20,
        "vocabulary": 12,
        "volume": 71.7,
        "difficulty": 2.67,
        "effort": 191.2,
        "level": 0.38,
        "bugs": 0.02,
        "time": 11,
        "intelligentContent": 26.89,
        "number_operators": 4,
        "number_operands": 16,
        "number_operators_unique": 3,
        "number_operands_unique": 9,
        "cloc": 0,
        "loc": 13,
        "lloc": 13,
        "mi": 62.44,
        "mIwoC": 62.44,
        "commentWeight": 0,
        "kanDefect": 0.22,
        "relativeStructuralComplexity": 9,
        "relativeDataComplexity": 0.25,
        "relativeSystemComplexity": 9.25,
        "totalStructuralComplexity": 9,
        "totalDataComplexity": 0.25,
        "totalSystemComplexity": 9.25,
        "package": "Edge\\QA\\Tools\\Analyzer\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "Edge\\QA\\Tools\\Analyzer\\Pdepend",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__invoke",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 2,
        "ccn": 2,
        "ccnMethodMax": 2,
        "externals": [
            "Edge\\QA\\Tools\\Tool"
        ],
        "parents": [
            "Edge\\QA\\Tools\\Tool"
        ],
        "lcom": 1,
        "length": 45,
        "vocabulary": 26,
        "volume": 211.52,
        "difficulty": 2.54,
        "effort": 538,
        "level": 0.39,
        "bugs": 0.07,
        "time": 30,
        "intelligentContent": 83.16,
        "number_operators": 6,
        "number_operands": 39,
        "number_operators_unique": 3,
        "number_operands_unique": 23,
        "cloc": 0,
        "loc": 15,
        "lloc": 15,
        "mi": 57.79,
        "mIwoC": 57.79,
        "commentWeight": 0,
        "kanDefect": 0.22,
        "relativeStructuralComplexity": 25,
        "relativeDataComplexity": 0.17,
        "relativeSystemComplexity": 25.17,
        "totalStructuralComplexity": 25,
        "totalDataComplexity": 0.17,
        "totalSystemComplexity": 25.17,
        "package": "Edge\\QA\\Tools\\Analyzer\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "Edge\\QA\\Tools\\Analyzer\\Phpstan",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__invoke",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getErrorFormatOption",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 1,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 6,
        "ccn": 5,
        "ccnMethodMax": 4,
        "externals": [
            "Edge\\QA\\Tools\\Tool",
            "Nette\\Neon\\Neon",
            "Nette\\Neon\\Neon"
        ],
        "parents": [
            "Edge\\QA\\Tools\\Tool"
        ],
        "lcom": 1,
        "length": 96,
        "vocabulary": 50,
        "volume": 541.81,
        "difficulty": 4.28,
        "effort": 2317.74,
        "level": 0.23,
        "bugs": 0.18,
        "time": 129,
        "intelligentContent": 126.66,
        "number_operators": 19,
        "number_operands": 77,
        "number_operators_unique": 5,
        "number_operands_unique": 45,
        "cloc": 0,
        "loc": 32,
        "lloc": 32,
        "mi": 47.35,
        "mIwoC": 47.35,
        "commentWeight": 0,
        "kanDefect": 0.29,
        "relativeStructuralComplexity": 64,
        "relativeDataComplexity": 0.44,
        "relativeSystemComplexity": 64.44,
        "totalStructuralComplexity": 128,
        "totalDataComplexity": 0.89,
        "totalSystemComplexity": 128.89,
        "package": "Edge\\QA\\Tools\\Analyzer\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 2,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "Edge\\QA\\Tools\\Analyzer\\PhpCsFixer",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__invoke",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 7,
        "ccn": 7,
        "ccnMethodMax": 7,
        "externals": [
            "Edge\\QA\\Tools\\Tool"
        ],
        "parents": [
            "Edge\\QA\\Tools\\Tool"
        ],
        "lcom": 1,
        "length": 75,
        "vocabulary": 44,
        "volume": 409.46,
        "difficulty": 4.74,
        "effort": 1939.53,
        "level": 0.21,
        "bugs": 0.14,
        "time": 108,
        "intelligentContent": 86.44,
        "number_operators": 15,
        "number_operands": 60,
        "number_operators_unique": 6,
        "number_operands_unique": 38,
        "cloc": 0,
        "loc": 29,
        "lloc": 29,
        "mi": 48.87,
        "mIwoC": 48.87,
        "commentWeight": 0,
        "kanDefect": 0.43,
        "relativeStructuralComplexity": 16,
        "relativeDataComplexity": 0.2,
        "relativeSystemComplexity": 16.2,
        "totalStructuralComplexity": 16,
        "totalDataComplexity": 0.2,
        "totalSystemComplexity": 16.2,
        "package": "Edge\\QA\\Tools\\Analyzer\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "Edge\\QA\\Tools\\Analyzer\\PhpMetrics",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__invoke",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 4,
        "ccn": 4,
        "ccnMethodMax": 4,
        "externals": [
            "Edge\\QA\\Tools\\Tool"
        ],
        "parents": [
            "Edge\\QA\\Tools\\Tool"
        ],
        "lcom": 1,
        "length": 65,
        "vocabulary": 32,
        "volume": 325,
        "difficulty": 3.57,
        "effort": 1160.71,
        "level": 0.28,
        "bugs": 0.11,
        "time": 64,
        "intelligentContent": 91,
        "number_operators": 15,
        "number_operands": 50,
        "number_operators_unique": 4,
        "number_operands_unique": 28,
        "cloc": 0,
        "loc": 27,
        "lloc": 27,
        "mi": 50.65,
        "mIwoC": 50.65,
        "commentWeight": 0,
        "kanDefect": 0.36,
        "relativeStructuralComplexity": 49,
        "relativeDataComplexity": 0.13,
        "relativeSystemComplexity": 49.13,
        "totalStructuralComplexity": 49,
        "totalDataComplexity": 0.13,
        "totalSystemComplexity": 49.13,
        "package": "Edge\\QA\\Tools\\Analyzer\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "Edge\\QA\\Tools\\Analyzer\\Phpcpd",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__invoke",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 6,
        "ccn": 6,
        "ccnMethodMax": 6,
        "externals": [
            "Edge\\QA\\Tools\\Tool"
        ],
        "parents": [
            "Edge\\QA\\Tools\\Tool"
        ],
        "lcom": 1,
        "length": 65,
        "vocabulary": 33,
        "volume": 327.89,
        "difficulty": 2.65,
        "effort": 868.9,
        "level": 0.38,
        "bugs": 0.11,
        "time": 48,
        "intelligentContent": 123.73,
        "number_operators": 12,
        "number_operands": 53,
        "number_operators_unique": 3,
        "number_operands_unique": 30,
        "cloc": 0,
        "loc": 24,
        "lloc": 24,
        "mi": 51.47,
        "mIwoC": 51.47,
        "commentWeight": 0,
        "kanDefect": 0.36,
        "relativeStructuralComplexity": 36,
        "relativeDataComplexity": 0.29,
        "relativeSystemComplexity": 36.29,
        "totalStructuralComplexity": 36,
        "totalDataComplexity": 0.29,
        "totalSystemComplexity": 36.29,
        "package": "Edge\\QA\\Tools\\Analyzer\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "Edge\\QA\\Tools\\Analyzer\\PhpMetricsV2",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__invoke",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 6,
        "ccn": 6,
        "ccnMethodMax": 6,
        "externals": [
            "Edge\\QA\\Tools\\Tool"
        ],
        "parents": [
            "Edge\\QA\\Tools\\Tool"
        ],
        "lcom": 1,
        "length": 73,
        "vocabulary": 29,
        "volume": 354.63,
        "difficulty": 5.73,
        "effort": 2031.75,
        "level": 0.17,
        "bugs": 0.12,
        "time": 113,
        "intelligentContent": 61.9,
        "number_operators": 18,
        "number_operands": 55,
        "number_operators_unique": 5,
        "number_operands_unique": 24,
        "cloc": 0,
        "loc": 29,
        "lloc": 29,
        "mi": 49.44,
        "mIwoC": 49.44,
        "commentWeight": 0,
        "kanDefect": 0.43,
        "relativeStructuralComplexity": 49,
        "relativeDataComplexity": 0.13,
        "relativeSystemComplexity": 49.13,
        "totalStructuralComplexity": 49,
        "totalDataComplexity": 0.13,
        "totalSystemComplexity": 49.13,
        "package": "Edge\\QA\\Tools\\Analyzer\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "Edge\\QA\\Tools\\Analyzer\\Psalm",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__invoke",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "updateProjectFiles",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "simpleXMLToPrettyString",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 3,
        "nbMethods": 3,
        "nbMethodsPrivate": 2,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 18,
        "ccn": 16,
        "ccnMethodMax": 9,
        "externals": [
            "Edge\\QA\\Tools\\Tool",
            "SimpleXMLElement",
            "SimpleXMLElement",
            "DOMDocument"
        ],
        "parents": [
            "Edge\\QA\\Tools\\Tool"
        ],
        "lcom": 1,
        "length": 138,
        "vocabulary": 54,
        "volume": 794.17,
        "difficulty": 5.61,
        "effort": 4457.1,
        "level": 0.18,
        "bugs": 0.26,
        "time": 248,
        "intelligentContent": 141.51,
        "number_operators": 28,
        "number_operands": 110,
        "number_operators_unique": 5,
        "number_operands_unique": 49,
        "cloc": 0,
        "loc": 61,
        "lloc": 61,
        "mi": 38.6,
        "mIwoC": 38.6,
        "commentWeight": 0,
        "kanDefect": 1.4,
        "relativeStructuralComplexity": 256,
        "relativeDataComplexity": 0.22,
        "relativeSystemComplexity": 256.22,
        "totalStructuralComplexity": 768,
        "totalDataComplexity": 0.65,
        "totalSystemComplexity": 768.65,
        "package": "Edge\\QA\\Tools\\Analyzer\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 3,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "Edge\\QA\\Tools\\Analyzer\\ParallelLint",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__invoke",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 1,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Edge\\QA\\Tools\\Tool"
        ],
        "parents": [
            "Edge\\QA\\Tools\\Tool"
        ],
        "lcom": 1,
        "length": 15,
        "vocabulary": 12,
        "volume": 53.77,
        "difficulty": 0.64,
        "effort": 34.22,
        "level": 1.57,
        "bugs": 0.02,
        "time": 2,
        "intelligentContent": 84.5,
        "number_operators": 1,
        "number_operands": 14,
        "number_operators_unique": 1,
        "number_operands_unique": 11,
        "cloc": 0,
        "loc": 9,
        "lloc": 9,
        "mi": 66.93,
        "mIwoC": 66.93,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 9,
        "relativeDataComplexity": 0.25,
        "relativeSystemComplexity": 9.25,
        "totalStructuralComplexity": 9,
        "totalDataComplexity": 0.25,
        "totalSystemComplexity": 9.25,
        "package": "Edge\\QA\\Tools\\Analyzer\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "Edge\\QA\\Tools\\Analyzer\\SecurityChecker",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__invoke",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 3,
        "ccn": 3,
        "ccnMethodMax": 3,
        "externals": [
            "Edge\\QA\\Tools\\Tool"
        ],
        "parents": [
            "Edge\\QA\\Tools\\Tool"
        ],
        "lcom": 1,
        "length": 31,
        "vocabulary": 21,
        "volume": 136.16,
        "difficulty": 2.82,
        "effort": 384.46,
        "level": 0.35,
        "bugs": 0.05,
        "time": 21,
        "intelligentContent": 48.22,
        "number_operators": 7,
        "number_operands": 24,
        "number_operators_unique": 4,
        "number_operands_unique": 17,
        "cloc": 0,
        "loc": 18,
        "lloc": 18,
        "mi": 57.27,
        "mIwoC": 57.27,
        "commentWeight": 0,
        "kanDefect": 0.45,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 0.5,
        "relativeSystemComplexity": 1.5,
        "totalStructuralComplexity": 1,
        "totalDataComplexity": 0.5,
        "totalSystemComplexity": 1.5,
        "package": "Edge\\QA\\Tools\\Analyzer\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "Edge\\QA\\Tools\\Analyzer\\Phpunit",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__invoke",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getFile",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 1,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 10,
        "ccn": 9,
        "ccnMethodMax": 6,
        "externals": [
            "Edge\\QA\\Tools\\Tool"
        ],
        "parents": [
            "Edge\\QA\\Tools\\Tool"
        ],
        "lcom": 1,
        "length": 110,
        "vocabulary": 39,
        "volume": 581.39,
        "difficulty": 5.37,
        "effort": 3122.92,
        "level": 0.19,
        "bugs": 0.19,
        "time": 173,
        "intelligentContent": 108.24,
        "number_operators": 16,
        "number_operands": 94,
        "number_operators_unique": 4,
        "number_operands_unique": 35,
        "cloc": 0,
        "loc": 35,
        "lloc": 35,
        "mi": 45.75,
        "mIwoC": 45.75,
        "commentWeight": 0,
        "kanDefect": 0.82,
        "relativeStructuralComplexity": 25,
        "relativeDataComplexity": 0.83,
        "relativeSystemComplexity": 25.83,
        "totalStructuralComplexity": 50,
        "totalDataComplexity": 1.67,
        "totalSystemComplexity": 51.67,
        "package": "Edge\\QA\\Tools\\Analyzer\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "Edge\\QA\\Tools\\GetVersions",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "getToolVersion",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "__invoke",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "findComposerPackages",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "analyzeTool",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "normalizeVersion",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "groupAuthors",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "loadVersionFromConsoleCommand",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "createSymfonyProcess",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getFirstLine",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "extractVersion",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 10,
        "nbMethods": 10,
        "nbMethodsPrivate": 8,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 24,
        "ccn": 15,
        "ccnMethodMax": 7,
        "externals": [
            "Symfony\\Component\\Process\\Process",
            "Symfony\\Component\\Process\\Process"
        ],
        "parents": [],
        "lcom": 1,
        "length": 255,
        "vocabulary": 62,
        "volume": 1518.32,
        "difficulty": 10.88,
        "effort": 16511.73,
        "level": 0.09,
        "bugs": 0.51,
        "time": 917,
        "intelligentContent": 139.62,
        "number_operators": 52,
        "number_operands": 203,
        "number_operators_unique": 6,
        "number_operands_unique": 56,
        "cloc": 0,
        "loc": 96,
        "lloc": 96,
        "mi": 32.47,
        "mIwoC": 32.47,
        "commentWeight": 0,
        "kanDefect": 0.96,
        "relativeStructuralComplexity": 144,
        "relativeDataComplexity": 1.32,
        "relativeSystemComplexity": 145.32,
        "totalStructuralComplexity": 1440,
        "totalDataComplexity": 13.23,
        "totalSystemComplexity": 1453.23,
        "package": "Edge\\QA\\Tools\\",
        "pageRank": 0.08,
        "afferentCoupling": 2,
        "efferentCoupling": 1,
        "instability": 0.33,
        "violations": {}
    },
    {
        "name": "Edge\\QA\\Tools\\AnalyzeResults",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": "setter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "__invoke",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 1,
        "wmc": 7,
        "ccn": 6,
        "ccnMethodMax": 6,
        "externals": [
            "Edge\\QA\\Options"
        ],
        "parents": [],
        "lcom": 1,
        "length": 80,
        "vocabulary": 28,
        "volume": 384.59,
        "difficulty": 8.73,
        "effort": 3356.41,
        "level": 0.11,
        "bugs": 0.13,
        "time": 186,
        "intelligentContent": 44.07,
        "number_operators": 16,
        "number_operands": 64,
        "number_operators_unique": 6,
        "number_operands_unique": 22,
        "cloc": 3,
        "loc": 33,
        "lloc": 30,
        "mi": 71.39,
        "mIwoC": 48.87,
        "commentWeight": 22.51,
        "kanDefect": 0.52,
        "relativeStructuralComplexity": 16,
        "relativeDataComplexity": 0.4,
        "relativeSystemComplexity": 16.4,
        "totalStructuralComplexity": 32,
        "totalDataComplexity": 0.8,
        "totalSystemComplexity": 32.8,
        "package": "Edge\\QA\\Tools\\",
        "pageRank": 0.01,
        "afferentCoupling": 1,
        "efferentCoupling": 1,
        "instability": 0.5,
        "violations": {}
    },
    {
        "name": "Edge\\QA\\Task\\RoboAdapter",
        "interface": false,
        "abstract": true,
        "final": false,
        "methods": [
            {
                "name": "taskPhpqaRunner",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "addArgToExec",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "isRoboVersionOne",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 3,
        "nbMethods": 3,
        "nbMethodsPrivate": 3,
        "nbMethodsPublic": 0,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 8,
        "ccn": 6,
        "ccnMethodMax": 4,
        "externals": [
            "class"
        ],
        "parents": [],
        "lcom": 1,
        "length": 45,
        "vocabulary": 18,
        "volume": 187.65,
        "difficulty": 4.57,
        "effort": 857.81,
        "level": 0.22,
        "bugs": 0.06,
        "time": 48,
        "intelligentContent": 41.05,
        "number_operators": 13,
        "number_operands": 32,
        "number_operators_unique": 4,
        "number_operands_unique": 14,
        "cloc": 0,
        "loc": 32,
        "lloc": 32,
        "mi": 50.44,
        "mIwoC": 50.44,
        "commentWeight": 0,
        "kanDefect": 0.36,
        "relativeStructuralComplexity": 16,
        "relativeDataComplexity": 1.4,
        "relativeSystemComplexity": 17.4,
        "totalStructuralComplexity": 48,
        "totalDataComplexity": 4.2,
        "totalSystemComplexity": 52.2,
        "package": "Edge\\QA\\Task\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "Edge\\QA\\Task\\TableSummary",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": "setter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "__invoke",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "result",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getStatus",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "writeln",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 5,
        "nbMethods": 4,
        "nbMethodsPrivate": 3,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 1,
        "wmc": 12,
        "ccn": 8,
        "ccnMethodMax": 4,
        "externals": [
            "Symfony\\Component\\Console\\Output\\OutputInterface",
            "Symfony\\Component\\Console\\Helper\\Table",
            "Symfony\\Component\\Console\\Helper\\TableSeparator"
        ],
        "parents": [],
        "lcom": 1,
        "length": 102,
        "vocabulary": 49,
        "volume": 572.7,
        "difficulty": 5,
        "effort": 2863.5,
        "level": 0.2,
        "bugs": 0.19,
        "time": 159,
        "intelligentContent": 114.54,
        "number_operators": 14,
        "number_operands": 88,
        "number_operators_unique": 5,
        "number_operands_unique": 44,
        "cloc": 1,
        "loc": 48,
        "lloc": 47,
        "mi": 54.23,
        "mIwoC": 43.14,
        "commentWeight": 11.09,
        "kanDefect": 0.66,
        "relativeStructuralComplexity": 36,
        "relativeDataComplexity": 0.6,
        "relativeSystemComplexity": 36.6,
        "totalStructuralComplexity": 180,
        "totalDataComplexity": 3,
        "totalSystemComplexity": 183,
        "package": "Edge\\QA\\Task\\",
        "pageRank": 0.01,
        "afferentCoupling": 1,
        "efferentCoupling": 3,
        "instability": 0.75,
        "violations": {}
    },
    {
        "name": "Edge\\QA\\Task\\NonParallelExecV0",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "startProgressIndicator",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "advanceProgressIndicator",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "stopProgressIndicator",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "printProcessResult",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 4,
        "nbMethods": 4,
        "nbMethodsPrivate": 4,
        "nbMethodsPublic": 0,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 5,
        "ccn": 2,
        "ccnMethodMax": 2,
        "externals": [
            "Edge\\QA\\Task\\NonParallelExecV1",
            "Symfony\\Component\\Console\\Helper\\ProgressBar",
            "Symfony\\Component\\Process\\Process"
        ],
        "parents": [
            "Edge\\QA\\Task\\NonParallelExecV1"
        ],
        "lcom": 1,
        "length": 30,
        "vocabulary": 12,
        "volume": 107.55,
        "difficulty": 4,
        "effort": 430.2,
        "level": 0.25,
        "bugs": 0.04,
        "time": 24,
        "intelligentContent": 26.89,
        "number_operators": 6,
        "number_operands": 24,
        "number_operators_unique": 3,
        "number_operands_unique": 9,
        "cloc": 1,
        "loc": 28,
        "lloc": 27,
        "mi": 68.71,
        "mIwoC": 54.28,
        "commentWeight": 14.43,
        "kanDefect": 0.22,
        "relativeStructuralComplexity": 49,
        "relativeDataComplexity": 0.06,
        "relativeSystemComplexity": 49.06,
        "totalStructuralComplexity": 196,
        "totalDataComplexity": 0.25,
        "totalSystemComplexity": 196.25,
        "package": "Edge\\QA\\Task\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 3,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "Edge\\QA\\Task\\NonParallelExecV1",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "run",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "printProcessResult",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 1,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 9,
        "ccn": 8,
        "ccnMethodMax": 7,
        "externals": [
            "Edge\\QA\\Task\\ParallelExec",
            "Robo\\Result",
            "Symfony\\Component\\Process\\Process"
        ],
        "parents": [
            "Edge\\QA\\Task\\ParallelExec"
        ],
        "lcom": 1,
        "length": 74,
        "vocabulary": 20,
        "volume": 319.82,
        "difficulty": 12.21,
        "effort": 3906.41,
        "level": 0.08,
        "bugs": 0.11,
        "time": 217,
        "intelligentContent": 26.18,
        "number_operators": 17,
        "number_operands": 57,
        "number_operators_unique": 6,
        "number_operands_unique": 14,
        "cloc": 10,
        "loc": 55,
        "lloc": 45,
        "mi": 76,
        "mIwoC": 45.32,
        "commentWeight": 30.68,
        "kanDefect": 1.12,
        "relativeStructuralComplexity": 324,
        "relativeDataComplexity": 0.08,
        "relativeSystemComplexity": 324.08,
        "totalStructuralComplexity": 648,
        "totalDataComplexity": 0.16,
        "totalSystemComplexity": 648.16,
        "package": "Edge\\QA\\Task\\",
        "pageRank": 0.01,
        "afferentCoupling": 1,
        "efferentCoupling": 3,
        "instability": 0.75,
        "violations": {}
    },
    {
        "name": "Edge\\QA\\Task\\AssetsLoader",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": "setter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "__invoke",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "downloadUrl",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "writeln",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 4,
        "nbMethods": 3,
        "nbMethodsPrivate": 2,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 1,
        "wmc": 8,
        "ccn": 5,
        "ccnMethodMax": 3,
        "externals": [
            "Symfony\\Component\\Console\\Output\\OutputInterface",
            "Edge\\QA\\Options",
            "Symfony\\Component\\Console\\Helper\\ProgressBar",
            "InvalidArgumentException"
        ],
        "parents": [],
        "lcom": 1,
        "length": 80,
        "vocabulary": 31,
        "volume": 396.34,
        "difficulty": 4.81,
        "effort": 1908.28,
        "level": 0.21,
        "bugs": 0.13,
        "time": 106,
        "intelligentContent": 82.32,
        "number_operators": 15,
        "number_operands": 65,
        "number_operators_unique": 4,
        "number_operands_unique": 27,
        "cloc": 1,
        "loc": 48,
        "lloc": 47,
        "mi": 55.75,
        "mIwoC": 44.66,
        "commentWeight": 11.09,
        "kanDefect": 0.59,
        "relativeStructuralComplexity": 25,
        "relativeDataComplexity": 0.75,
        "relativeSystemComplexity": 25.75,
        "totalStructuralComplexity": 100,
        "totalDataComplexity": 3,
        "totalSystemComplexity": 103,
        "package": "Edge\\QA\\Task\\",
        "pageRank": 0.01,
        "afferentCoupling": 1,
        "efferentCoupling": 4,
        "instability": 0.8,
        "violations": {}
    },
    {
        "name": "Edge\\QA\\Task\\TableVersions",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": "setter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "__invoke",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 1,
        "wmc": 3,
        "ccn": 2,
        "ccnMethodMax": 2,
        "externals": [
            "Symfony\\Component\\Console\\Output\\OutputInterface",
            "Symfony\\Component\\Console\\Helper\\Table"
        ],
        "parents": [],
        "lcom": 1,
        "length": 25,
        "vocabulary": 15,
        "volume": 97.67,
        "difficulty": 0.82,
        "effort": 80.23,
        "level": 1.22,
        "bugs": 0.03,
        "time": 4,
        "intelligentContent": 118.91,
        "number_operators": 2,
        "number_operands": 23,
        "number_operators_unique": 1,
        "number_operands_unique": 14,
        "cloc": 0,
        "loc": 18,
        "lloc": 18,
        "mi": 58.42,
        "mIwoC": 58.42,
        "commentWeight": 0,
        "kanDefect": 0.38,
        "relativeStructuralComplexity": 9,
        "relativeDataComplexity": 0.25,
        "relativeSystemComplexity": 9.25,
        "totalStructuralComplexity": 18,
        "totalDataComplexity": 0.5,
        "totalSystemComplexity": 18.5,
        "package": "Edge\\QA\\Task\\",
        "pageRank": 0.01,
        "afferentCoupling": 1,
        "efferentCoupling": 2,
        "instability": 0.67,
        "violations": {}
    },
    {
        "name": "Edge\\QA\\Task\\ParallelExec",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "process",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 1,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Robo\\Task\\Base\\ParallelExec"
        ],
        "parents": [
            "Robo\\Task\\Base\\ParallelExec"
        ],
        "lcom": 1,
        "length": 4,
        "vocabulary": 3,
        "volume": 6.34,
        "difficulty": 0.75,
        "effort": 4.75,
        "level": 1.33,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 8.45,
        "number_operators": 1,
        "number_operands": 3,
        "number_operators_unique": 1,
        "number_operands_unique": 2,
        "cloc": 4,
        "loc": 13,
        "lloc": 9,
        "mi": 111.3,
        "mIwoC": 73.43,
        "commentWeight": 37.87,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 1,
        "relativeSystemComplexity": 2,
        "totalStructuralComplexity": 1,
        "totalDataComplexity": 1,
        "totalSystemComplexity": 2,
        "package": "Edge\\QA\\Task\\",
        "pageRank": 0.01,
        "afferentCoupling": 1,
        "efferentCoupling": 1,
        "instability": 0.5,
        "violations": {}
    },
    {
        "name": "Edge\\QA\\IgnoredPaths",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "setOS",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "csvToArray",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "phpcs",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "pdepend",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "phpmd",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "pdependWindowsFilter",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "phpmetrics",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "phpmetrics2",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "bergmann",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "parallelLint",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "phpstan",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "psalm",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "ignore",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "implode",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 15,
        "nbMethods": 14,
        "nbMethodsPrivate": 4,
        "nbMethodsPublic": 10,
        "nbMethodsGetter": 1,
        "nbMethodsSetters": 0,
        "wmc": 21,
        "ccn": 7,
        "ccnMethodMax": 3,
        "externals": [],
        "parents": [],
        "lcom": 1,
        "length": 148,
        "vocabulary": 49,
        "volume": 830.98,
        "difficulty": 8.16,
        "effort": 6783.09,
        "level": 0.12,
        "bugs": 0.28,
        "time": 377,
        "intelligentContent": 101.8,
        "number_operators": 31,
        "number_operands": 117,
        "number_operators_unique": 6,
        "number_operands_unique": 43,
        "cloc": 55,
        "loc": 88,
        "lloc": 35,
        "mi": 91.97,
        "mIwoC": 44.93,
        "commentWeight": 47.04,
        "kanDefect": 0.43,
        "relativeStructuralComplexity": 25,
        "relativeDataComplexity": 2.98,
        "relativeSystemComplexity": 27.98,
        "totalStructuralComplexity": 375,
        "totalDataComplexity": 44.67,
        "totalSystemComplexity": 419.67,
        "package": "Edge\\QA\\",
        "pageRank": 0.1,
        "afferentCoupling": 2,
        "efferentCoupling": 0,
        "instability": 0,
        "violations": {}
    },
    {
        "name": "Edge\\QA\\RunningTool",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "isInstalled",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "isAtLeastOneClassInstalled",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "hasOutput",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "buildOption",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getAllowedErrorsCount",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "analyzeResult",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "evaluteErrorsCount",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "areErrorsIgnored",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getXmlFiles",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getEscapedXmlFile",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getMainXml",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getHtmlRootReports",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "__toString",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 14,
        "nbMethods": 11,
        "nbMethodsPrivate": 4,
        "nbMethodsPublic": 7,
        "nbMethodsGetter": 3,
        "nbMethodsSetters": 0,
        "wmc": 32,
        "ccn": 19,
        "ccnMethodMax": 8,
        "externals": [],
        "parents": [],
        "lcom": 1,
        "length": 184,
        "vocabulary": 49,
        "volume": 1033.11,
        "difficulty": 17.18,
        "effort": 17748.24,
        "level": 0.06,
        "bugs": 0.34,
        "time": 986,
        "intelligentContent": 60.14,
        "number_operators": 50,
        "number_operands": 134,
        "number_operators_unique": 10,
        "number_operands_unique": 39,
        "cloc": 1,
        "loc": 112,
        "lloc": 111,
        "mi": 39.02,
        "mIwoC": 31.72,
        "commentWeight": 7.29,
        "kanDefect": 0.96,
        "relativeStructuralComplexity": 36,
        "relativeDataComplexity": 2.94,
        "relativeSystemComplexity": 38.94,
        "totalStructuralComplexity": 504,
        "totalDataComplexity": 41.14,
        "totalSystemComplexity": 545.14,
        "package": "Edge\\QA\\",
        "pageRank": 0.18,
        "afferentCoupling": 5,
        "efferentCoupling": 0,
        "instability": 0,
        "violations": {}
    }
]