#!/usr/bin/env bash

APP_DIR="./"
DOCKER_REPO="zdenekdrahos/phpqa"
DOCKER_FILE=".docker/Dockerfile"
DOCKER_TAG=""

run () {
    load_docker_variables
    build_docker_image
}

load_docker_variables () {
    DOCKER_TAG="$DOCKER_REPO:${TRAVIS_TAG:-${TRAVIS_COMMIT:0:7}}"

    echo "Dockefile: $DOCKER_FILE"
    echo "Build context: $APP_DIR"
    echo "Publish image: $DOCKER_TAG"
    echo
}

build_docker_image () {
    set -e
    time docker build --file $DOCKER_FILE --tag $DOCKER_TAG $APP_DIR
    docker run --rm -it $DOCKER_TAG phpqa tools

    if [ -z "$TRAVIS_TAG" ]; then
        echo "Docker image is published only if the current build is for a git tag"
        exit 0
    fi
    docker login --username $DOCKER_USER --password $DOCKER_TOKEN
    time docker push $DOCKER_TAG
}

run
