#!/usr/bin/env bash
#
# CI_GIT_REF=<refs/heads/feature-branch|refs/tags/v...> CI_COMMIT_SHA=$(git rev-parse --short HEAD) .docker/build-image

APP_DIR="./"
DOCKER_REPO="edgedesigncz/phpqa"
DOCKER_FILE=".docker/Dockerfile"
DOCKER_REGISTRY=${DOCKER_REGISTRY:-"ghcr.io"}
DOCKER_TAG=""
GIT_VERSION=""
GIT_TAG=""
PHP_VERSION=${PHP_VERSION:-"7.2"}
COMPOSER_VERSION=""
UPDATE_COMPOSER=""

run () {
    analyze_git_ref
    load_docker_variables
    build_docker_image
}

analyze_git_ref () {
    GIT_TAG=""
    if [[ "${CI_GIT_REF:0:10}" = "refs/tags/" ]]; then
        GIT_TAG=${CI_GIT_REF:10}
    fi
    GIT_VERSION="${GIT_TAG:-${CI_COMMIT_SHA:0:7}}"
}

load_docker_variables () {
    if [[ $PHP_VERSION == "7.2" ]]; then
        COMPOSER_VERSION="1.8.0"
        UPDATE_COMPOSER="no"
    elif [[ $PHP_VERSION == "8.1" ]]; then
        COMPOSER_VERSION="2.2.12"
        UPDATE_COMPOSER="yes"
    else
        echo "PHP version $PHP_VERSION not supported"
        exit 1
    fi
    DOCKER_TAG="$DOCKER_REGISTRY/$DOCKER_REPO:$GIT_VERSION-php$PHP_VERSION"

    echo "Dockefile: $DOCKER_FILE"
    echo "Build vars: COMPOSER_VERSION=$COMPOSER_VERSION UPDATE_COMPOSER=$UPDATE_COMPOSER"
    echo "Build context: $APP_DIR"
    echo "Publish image: $DOCKER_TAG"
    echo
}

build_docker_image () {
    set -e
    time docker build \
        --file $DOCKER_FILE \
        --tag $DOCKER_TAG $APP_DIR \
        --build-arg "COMPOSER_VERSION=$COMPOSER_VERSION" \
        --build-arg "UPDATE_COMPOSER=$UPDATE_COMPOSER"
    docker run --rm -t $DOCKER_TAG sh -c "php --version && composer --version && composer outdated --direct --all && phpqa tools"

    docker login --username $DOCKER_USER --password $DOCKER_TOKEN $DOCKER_REGISTRY
    time docker push $DOCKER_TAG
}

run
