name: PHPQA Docker

# `push tag && master branch` is complicated... (checkout + fetch-depth:0 + find git branch from detached state)
# https://dh1tw.de/2019/12/real-life-ci/cd-pipelines-with-github-actions/#insufficient-filtering
# Release build is not visible from commit, but it's better than manually building docker images
# https://stackoverflow.com/a/59894223, https://stackoverflow.com/a/57983436
on:
  release:
    types: [created]

jobs:
  phpqa:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Build docker
      env:
        CI_GIT_REF: ${{ github.ref }}
        CI_COMMIT_SHA: ${{ github.sha }}
        DOCKER_USER: ${{ github.actor }}
        DOCKER_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        DOCKER_REGISTRY: ghcr.io
      run: |
        PHP_VERSION=7.2 .docker/build-image
        PHP_VERSION=8.1 .docker/build-image
